#pragma clang diagnostic ignored "-Wunused-variable"
#pragma clang diagnostic ignored "-Wmissing-prototypes"

#include <metal_stdlib>
#include <simd/simd.h>
#include <metal_atomic>

using namespace metal;

// The required alignment of a linear texture of R32Uint format.
constant uint spvLinearTextureAlignmentOverride [[function_constant(65535)]];
constant uint spvLinearTextureAlignment = is_function_constant_defined(spvLinearTextureAlignmentOverride) ? spvLinearTextureAlignmentOverride : 4;
// Returns buffer coords corresponding to 2D texture coords for emulating 2D texture atomics
#define spvImage2DAtomicCoord(tc, tex) (((((tex).get_width() +  spvLinearTextureAlignment / 4 - 1) & ~( spvLinearTextureAlignment / 4 - 1)) * (tc).y) + (tc).x)

struct OutputSSBO
{
    float4 out_value;
    uint out_atomic;
    int2 out_size;
};

constant uint3 gl_WorkGroupSize [[maybe_unused]] = uint3(1u);

kernel void main0(device OutputSSBO& _22 [[buffer(0)]], texture2d<float> readImage [[texture(0)]], texture2d<float, access::write> writeImage [[texture(1)]], texture2d<uint> atomicImage [[texture(2)]], device atomic_uint* atomicImage_atomic [[buffer(1)]], uint3 gl_GlobalInvocationID [[thread_position_in_grid]])
{
    int2 _17 = int2(gl_GlobalInvocationID.xy);
    float4 _29 = (!is_null_texture(readImage) ? (((uint(_17.x) < readImage.get_width()) && (uint(_17.y) < readImage.get_height())) ? readImage.read(uint2(_17)) : float4(0, 0, 0, 0)) : float4(0, 0, 0, 0));
    _22.out_value = _29;
    if ((((!is_null_texture(writeImage)) && (uint(_17.x) < writeImage.get_width())) && (uint(_17.y) < writeImage.get_height())))
    {
        writeImage.write(float4(1.0, 2.0, 3.0, 4.0), uint2(_17));
    }
    uint _49;
    if ((((!is_null_texture(atomicImage)) && (uint(_17.x) < atomicImage.get_width())) && (uint(_17.y) < atomicImage.get_height())))
    {
        _49 = atomic_fetch_add_explicit((device atomic_uint*)&atomicImage_atomic[spvImage2DAtomicCoord(_17, atomicImage)], 1u, memory_order_relaxed);
    }
    else
    {
        _49 = {};
    }
    _22.out_atomic = _49;
    _22.out_size = (is_null_texture(readImage) ? int2(0) : int2(readImage.get_width(), readImage.get_height()));
}

